framework:
    messenger:
        # Uncomment this (and the failed transport below) to send failed messages to this transport for later handling.
        failure_transport: failed

        transports:
            # https://symfony.com/doc/current/messenger.html#transport-configuration
            async: '%env(MESSENGER_TRANSPORT_DSN)%'
            failed: 'doctrine://default?queue_name=failed'
            sync: 'sync://'

        routing:
            # Route your messages to the transports
            'Massive\Bundle\VCloudBundle\Thing\Application\Message\ImportClassificationMessage': sync
            'Massive\Bundle\VCloudBundle\Thing\Application\Message\RemoveClassificationMessage': sync
            'Massive\Bundle\VCloudBundle\Thing\Application\Message\ImportThingMessage': sync
            'Massive\Bundle\VCloudBundle\Thing\Application\Message\ImportImageObjectMessage': async
            'Massive\Bundle\VCloudBundle\Search\Application\Message\IndexThingMessage': async
            'Massive\Bundle\VCloudBundle\Search\Application\Message\DeindexThingMessage': async
